name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MNEMONIC: ${{ secrets.MNEMONIC }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install and compile
        run: |
          yarn
          yarn compile

      - name: Perform unit test
        run: |
          yarn test